plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.192'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    maven {
        url = "https://www.cursemaven.com"
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // Applied Energistics 2 Base
    compileOnly "curse.maven:applied-energistics-2-223794:6890346"
    runtimeOnly "curse.maven:applied-energistics-2-223794:6890346"

    implementation "net.neoforged:neoforge:${neo_version}"

    implementation "curse.maven:titanium-287342:6443608"
    implementation "curse.maven:guideme-1173950:6488254"

    implementation "curse.maven:athena-841890:5629395"
    implementation "curse.maven:architectury-419699:5786327"
    implementation "curse.maven:owolib-532610:5945693"
    implementation "curse.maven:geckolib-388172:6920810"
    implementation "curse.maven:glodium-957920:5821676"

    implementation "curse.maven:ftlibrary-404465:6466106"
    implementation "curse.maven:ftpessential-410811:6179042"

    implementation "curse.maven:rhino-416294:6000610"
    implementation "curse.maven:kubejs-238086:5810100"
    implementation "curse.maven:jade-324717:6011258"
    implementation "curse.maven:trashcans-394535:5891067"
    implementation "curse.maven:supermarticonfig-438332:5546996"
    implementation "curse.maven:supermarticore-454372:6076757"

    compileOnly "curse.maven:extendedae-892005:9044672"
    // localRuntime "curse.maven:extendedae-892005:9044672"

    compileOnly "curse.maven:extendedae-1337639:8998231"
    // localRuntime "curse.maven:extendedae-1337639:8998231"

    compileOnly "curse.maven:advancedae-1084104:6939457"
    // localRuntime "curse.maven:advancedae-1084104:6939457"

    compileOnly "curse.maven:jei-238222:8870333"
    // runtimeOnly "curse.maven:jei-238222:8870333"

    compileOnly "curse.maven:ae2-wcwt-1546802:8970875"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}